services:
  nuvia-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nuvia
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"